### ISSUE TITLE
Diffractive_chain for spheres

### ISSUE THREAD

**Issue by vxb004** [plasmonics/cda#4]
Sir,
I changed the a and b (semi-axes) to same size to make the particles a sphere and was able to produce an image with N=10 as you can see in the attached image. However, I'm not able to incorporate these changes in the final spectra of extinction, absorption and scattering.

Also I tried finding the epsAu source file to edit the arguments like refractive index, plasmon wavelength etc. But when I go to dielectric->demo->I do not find epsAu. Is there a way to edit the source file of 
![chain of 10 spherical particles](https://cloud.githubusercontent.com/assets/19959972/16129423/5408810a-33ca-11e6-9d3a-f256b0c7fb63.JPG)
epsAu?

Thanks a lot.
Best Regards,
Vin

**Comment by baptiste** [comment]
`epsAu` is in the dielectric package

**Comment by vxb004** [comment]
I checked in dielectric->demo-> however, there are only Si.r, AuJC.r and AgPalik.r files.

I checked other folders in dielectric such as data, Meta, R, rawdata, etc. But I couldn't find epsAu. I downloaded the following version of dielectric :r-release: dielectric_0.2.3.zip.

When I say "edit(epsAu) in R workspace and click enter, I'm able to view epsAu content, however, when I try to find the sourcefile for editing it, I'm not able to locate it in dielectric. Thank you!

Best Regards,
Vin

**Comment by baptiste** [comment]
I'm afraid this is not an issue directly related to the `cda` package, so this is not the best place to discuss it. If you need help with the R language and the structure of R packages, I suggest you ask a question on StackOverflow.com, with a minimal reproducible example. Reading the _Introduction to R_ manual may also be helpful.

Feel free to ask specific cda-related issues here, but please do include a reproducible minimal example, otherwise I am unable to provide assistance.
